/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteRouteImport } from './routes/home/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as HomeWhyFeshiaIndexRouteImport } from './routes/home/why-feshia/index'
import { Route as HomeWhatWeDoIndexRouteImport } from './routes/home/what-we-do/index'
import { Route as HomeUniversitySearchIndexRouteImport } from './routes/home/university-search/index'
import { Route as HomeStudentBlogIndexRouteImport } from './routes/home/student-blog/index'
import { Route as HomePartnersIndexRouteImport } from './routes/home/partners/index'
import { Route as HomeInstitutionIndexRouteImport } from './routes/home/institution/index'
import { Route as HomeFaqsIndexRouteImport } from './routes/home/faqs/index'
import { Route as HomeEventsIndexRouteImport } from './routes/home/events/index'
import { Route as HomeConsultantIndexRouteImport } from './routes/home/consultant/index'
import { Route as HomeBookAppointmentIndexRouteImport } from './routes/home/book-appointment/index'
import { Route as HomeAboutIndexRouteImport } from './routes/home/about/index'
import { Route as AuthAdminIndexRouteImport } from './routes/auth/admin/index'

const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeWhyFeshiaIndexRoute = HomeWhyFeshiaIndexRouteImport.update({
  id: '/why-feshia/',
  path: '/why-feshia/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeWhatWeDoIndexRoute = HomeWhatWeDoIndexRouteImport.update({
  id: '/what-we-do/',
  path: '/what-we-do/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeUniversitySearchIndexRoute =
  HomeUniversitySearchIndexRouteImport.update({
    id: '/university-search/',
    path: '/university-search/',
    getParentRoute: () => HomeRouteRoute,
  } as any)
const HomeStudentBlogIndexRoute = HomeStudentBlogIndexRouteImport.update({
  id: '/student-blog/',
  path: '/student-blog/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomePartnersIndexRoute = HomePartnersIndexRouteImport.update({
  id: '/partners/',
  path: '/partners/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeInstitutionIndexRoute = HomeInstitutionIndexRouteImport.update({
  id: '/institution/',
  path: '/institution/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeFaqsIndexRoute = HomeFaqsIndexRouteImport.update({
  id: '/faqs/',
  path: '/faqs/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeEventsIndexRoute = HomeEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeConsultantIndexRoute = HomeConsultantIndexRouteImport.update({
  id: '/consultant/',
  path: '/consultant/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeBookAppointmentIndexRoute =
  HomeBookAppointmentIndexRouteImport.update({
    id: '/book-appointment/',
    path: '/book-appointment/',
    getParentRoute: () => HomeRouteRoute,
  } as any)
const HomeAboutIndexRoute = HomeAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: '/auth/admin/',
  path: '/auth/admin/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRouteRouteWithChildren
  '/home/': typeof HomeIndexRoute
  '/auth/admin': typeof AuthAdminIndexRoute
  '/home/about': typeof HomeAboutIndexRoute
  '/home/book-appointment': typeof HomeBookAppointmentIndexRoute
  '/home/consultant': typeof HomeConsultantIndexRoute
  '/home/events': typeof HomeEventsIndexRoute
  '/home/faqs': typeof HomeFaqsIndexRoute
  '/home/institution': typeof HomeInstitutionIndexRoute
  '/home/partners': typeof HomePartnersIndexRoute
  '/home/student-blog': typeof HomeStudentBlogIndexRoute
  '/home/university-search': typeof HomeUniversitySearchIndexRoute
  '/home/what-we-do': typeof HomeWhatWeDoIndexRoute
  '/home/why-feshia': typeof HomeWhyFeshiaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeIndexRoute
  '/auth/admin': typeof AuthAdminIndexRoute
  '/home/about': typeof HomeAboutIndexRoute
  '/home/book-appointment': typeof HomeBookAppointmentIndexRoute
  '/home/consultant': typeof HomeConsultantIndexRoute
  '/home/events': typeof HomeEventsIndexRoute
  '/home/faqs': typeof HomeFaqsIndexRoute
  '/home/institution': typeof HomeInstitutionIndexRoute
  '/home/partners': typeof HomePartnersIndexRoute
  '/home/student-blog': typeof HomeStudentBlogIndexRoute
  '/home/university-search': typeof HomeUniversitySearchIndexRoute
  '/home/what-we-do': typeof HomeWhatWeDoIndexRoute
  '/home/why-feshia': typeof HomeWhyFeshiaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRouteRouteWithChildren
  '/home/': typeof HomeIndexRoute
  '/auth/admin/': typeof AuthAdminIndexRoute
  '/home/about/': typeof HomeAboutIndexRoute
  '/home/book-appointment/': typeof HomeBookAppointmentIndexRoute
  '/home/consultant/': typeof HomeConsultantIndexRoute
  '/home/events/': typeof HomeEventsIndexRoute
  '/home/faqs/': typeof HomeFaqsIndexRoute
  '/home/institution/': typeof HomeInstitutionIndexRoute
  '/home/partners/': typeof HomePartnersIndexRoute
  '/home/student-blog/': typeof HomeStudentBlogIndexRoute
  '/home/university-search/': typeof HomeUniversitySearchIndexRoute
  '/home/what-we-do/': typeof HomeWhatWeDoIndexRoute
  '/home/why-feshia/': typeof HomeWhyFeshiaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/home/'
    | '/auth/admin'
    | '/home/about'
    | '/home/book-appointment'
    | '/home/consultant'
    | '/home/events'
    | '/home/faqs'
    | '/home/institution'
    | '/home/partners'
    | '/home/student-blog'
    | '/home/university-search'
    | '/home/what-we-do'
    | '/home/why-feshia'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/auth/admin'
    | '/home/about'
    | '/home/book-appointment'
    | '/home/consultant'
    | '/home/events'
    | '/home/faqs'
    | '/home/institution'
    | '/home/partners'
    | '/home/student-blog'
    | '/home/university-search'
    | '/home/what-we-do'
    | '/home/why-feshia'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/home/'
    | '/auth/admin/'
    | '/home/about/'
    | '/home/book-appointment/'
    | '/home/consultant/'
    | '/home/events/'
    | '/home/faqs/'
    | '/home/institution/'
    | '/home/partners/'
    | '/home/student-blog/'
    | '/home/university-search/'
    | '/home/what-we-do/'
    | '/home/why-feshia/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/why-feshia/': {
      id: '/home/why-feshia/'
      path: '/why-feshia'
      fullPath: '/home/why-feshia'
      preLoaderRoute: typeof HomeWhyFeshiaIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/what-we-do/': {
      id: '/home/what-we-do/'
      path: '/what-we-do'
      fullPath: '/home/what-we-do'
      preLoaderRoute: typeof HomeWhatWeDoIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/university-search/': {
      id: '/home/university-search/'
      path: '/university-search'
      fullPath: '/home/university-search'
      preLoaderRoute: typeof HomeUniversitySearchIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/student-blog/': {
      id: '/home/student-blog/'
      path: '/student-blog'
      fullPath: '/home/student-blog'
      preLoaderRoute: typeof HomeStudentBlogIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/partners/': {
      id: '/home/partners/'
      path: '/partners'
      fullPath: '/home/partners'
      preLoaderRoute: typeof HomePartnersIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/institution/': {
      id: '/home/institution/'
      path: '/institution'
      fullPath: '/home/institution'
      preLoaderRoute: typeof HomeInstitutionIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/faqs/': {
      id: '/home/faqs/'
      path: '/faqs'
      fullPath: '/home/faqs'
      preLoaderRoute: typeof HomeFaqsIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/events/': {
      id: '/home/events/'
      path: '/events'
      fullPath: '/home/events'
      preLoaderRoute: typeof HomeEventsIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/consultant/': {
      id: '/home/consultant/'
      path: '/consultant'
      fullPath: '/home/consultant'
      preLoaderRoute: typeof HomeConsultantIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/book-appointment/': {
      id: '/home/book-appointment/'
      path: '/book-appointment'
      fullPath: '/home/book-appointment'
      preLoaderRoute: typeof HomeBookAppointmentIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/about/': {
      id: '/home/about/'
      path: '/about'
      fullPath: '/home/about'
      preLoaderRoute: typeof HomeAboutIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/auth/admin/': {
      id: '/auth/admin/'
      path: '/auth/admin'
      fullPath: '/auth/admin'
      preLoaderRoute: typeof AuthAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HomeRouteRouteChildren {
  HomeIndexRoute: typeof HomeIndexRoute
  HomeAboutIndexRoute: typeof HomeAboutIndexRoute
  HomeBookAppointmentIndexRoute: typeof HomeBookAppointmentIndexRoute
  HomeConsultantIndexRoute: typeof HomeConsultantIndexRoute
  HomeEventsIndexRoute: typeof HomeEventsIndexRoute
  HomeFaqsIndexRoute: typeof HomeFaqsIndexRoute
  HomeInstitutionIndexRoute: typeof HomeInstitutionIndexRoute
  HomePartnersIndexRoute: typeof HomePartnersIndexRoute
  HomeStudentBlogIndexRoute: typeof HomeStudentBlogIndexRoute
  HomeUniversitySearchIndexRoute: typeof HomeUniversitySearchIndexRoute
  HomeWhatWeDoIndexRoute: typeof HomeWhatWeDoIndexRoute
  HomeWhyFeshiaIndexRoute: typeof HomeWhyFeshiaIndexRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeIndexRoute: HomeIndexRoute,
  HomeAboutIndexRoute: HomeAboutIndexRoute,
  HomeBookAppointmentIndexRoute: HomeBookAppointmentIndexRoute,
  HomeConsultantIndexRoute: HomeConsultantIndexRoute,
  HomeEventsIndexRoute: HomeEventsIndexRoute,
  HomeFaqsIndexRoute: HomeFaqsIndexRoute,
  HomeInstitutionIndexRoute: HomeInstitutionIndexRoute,
  HomePartnersIndexRoute: HomePartnersIndexRoute,
  HomeStudentBlogIndexRoute: HomeStudentBlogIndexRoute,
  HomeUniversitySearchIndexRoute: HomeUniversitySearchIndexRoute,
  HomeWhatWeDoIndexRoute: HomeWhatWeDoIndexRoute,
  HomeWhyFeshiaIndexRoute: HomeWhyFeshiaIndexRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRouteRoute: HomeRouteRouteWithChildren,
  AuthAdminIndexRoute: AuthAdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
