/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteRouteImport } from './routes/home/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminDashboardRouteRouteImport } from './routes/admin/dashboard/route'
import { Route as HomeWhyFeshiaIndexRouteImport } from './routes/home/why-feshia/index'
import { Route as HomeWhatWeDoIndexRouteImport } from './routes/home/what-we-do/index'
import { Route as HomeUniversitySearchIndexRouteImport } from './routes/home/university-search/index'
import { Route as HomeStudentBlogIndexRouteImport } from './routes/home/student-blog/index'
import { Route as HomePartnersIndexRouteImport } from './routes/home/partners/index'
import { Route as HomeInstitutionIndexRouteImport } from './routes/home/institution/index'
import { Route as HomeFaqsIndexRouteImport } from './routes/home/faqs/index'
import { Route as HomeEventsIndexRouteImport } from './routes/home/events/index'
import { Route as HomeConsultantIndexRouteImport } from './routes/home/consultant/index'
import { Route as HomeBookAppointmentIndexRouteImport } from './routes/home/book-appointment/index'
import { Route as HomeAboutIndexRouteImport } from './routes/home/about/index'
import { Route as AuthAdminIndexRouteImport } from './routes/auth/admin/index'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/dashboard/index'
import { Route as AdminDashboardSettingsRouteImport } from './routes/admin/dashboard/settings'
import { Route as AdminDashboardPartnersRouteImport } from './routes/admin/dashboard/partners'
import { Route as AdminDashboardInvestorsRouteImport } from './routes/admin/dashboard/investors'
import { Route as AdminDashboardAnnouncementsRouteImport } from './routes/admin/dashboard/announcements'
import { Route as AdminDashboardProspectsIndexRouteImport } from './routes/admin/dashboard/prospects/index'
import { Route as AdminDashboardInvestorsIndexRouteImport } from './routes/admin/dashboard/investors/index'
import { Route as AdminDashboardTransactionsReceiptsRouteImport } from './routes/admin/dashboard/transactions/receipts'
import { Route as AdminDashboardTransactionsPaymentsRouteImport } from './routes/admin/dashboard/transactions/payments'
import { Route as AdminDashboardInvestorsInvestorIdRouteImport } from './routes/admin/dashboard/investors/$investorId'

const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRouteRoute = AdminDashboardRouteRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeWhyFeshiaIndexRoute = HomeWhyFeshiaIndexRouteImport.update({
  id: '/why-feshia/',
  path: '/why-feshia/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeWhatWeDoIndexRoute = HomeWhatWeDoIndexRouteImport.update({
  id: '/what-we-do/',
  path: '/what-we-do/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeUniversitySearchIndexRoute =
  HomeUniversitySearchIndexRouteImport.update({
    id: '/university-search/',
    path: '/university-search/',
    getParentRoute: () => HomeRouteRoute,
  } as any)
const HomeStudentBlogIndexRoute = HomeStudentBlogIndexRouteImport.update({
  id: '/student-blog/',
  path: '/student-blog/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomePartnersIndexRoute = HomePartnersIndexRouteImport.update({
  id: '/partners/',
  path: '/partners/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeInstitutionIndexRoute = HomeInstitutionIndexRouteImport.update({
  id: '/institution/',
  path: '/institution/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeFaqsIndexRoute = HomeFaqsIndexRouteImport.update({
  id: '/faqs/',
  path: '/faqs/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeEventsIndexRoute = HomeEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeConsultantIndexRoute = HomeConsultantIndexRouteImport.update({
  id: '/consultant/',
  path: '/consultant/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeBookAppointmentIndexRoute =
  HomeBookAppointmentIndexRouteImport.update({
    id: '/book-appointment/',
    path: '/book-appointment/',
    getParentRoute: () => HomeRouteRoute,
  } as any)
const HomeAboutIndexRoute = HomeAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: '/auth/admin/',
  path: '/auth/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDashboardRouteRoute,
} as any)
const AdminDashboardSettingsRoute = AdminDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminDashboardRouteRoute,
} as any)
const AdminDashboardPartnersRoute = AdminDashboardPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AdminDashboardRouteRoute,
} as any)
const AdminDashboardInvestorsRoute = AdminDashboardInvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => AdminDashboardRouteRoute,
} as any)
const AdminDashboardAnnouncementsRoute =
  AdminDashboardAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardProspectsIndexRoute =
  AdminDashboardProspectsIndexRouteImport.update({
    id: '/prospects/',
    path: '/prospects/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardInvestorsIndexRoute =
  AdminDashboardInvestorsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminDashboardInvestorsRoute,
  } as any)
const AdminDashboardTransactionsReceiptsRoute =
  AdminDashboardTransactionsReceiptsRouteImport.update({
    id: '/transactions/receipts',
    path: '/transactions/receipts',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardTransactionsPaymentsRoute =
  AdminDashboardTransactionsPaymentsRouteImport.update({
    id: '/transactions/payments',
    path: '/transactions/payments',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardInvestorsInvestorIdRoute =
  AdminDashboardInvestorsInvestorIdRouteImport.update({
    id: '/$investorId',
    path: '/$investorId',
    getParentRoute: () => AdminDashboardInvestorsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRouteRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRouteRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/home/': typeof HomeIndexRoute
  '/admin/dashboard/announcements': typeof AdminDashboardAnnouncementsRoute
  '/admin/dashboard/investors': typeof AdminDashboardInvestorsRouteWithChildren
  '/admin/dashboard/partners': typeof AdminDashboardPartnersRoute
  '/admin/dashboard/settings': typeof AdminDashboardSettingsRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/auth/admin': typeof AuthAdminIndexRoute
  '/home/about': typeof HomeAboutIndexRoute
  '/home/book-appointment': typeof HomeBookAppointmentIndexRoute
  '/home/consultant': typeof HomeConsultantIndexRoute
  '/home/events': typeof HomeEventsIndexRoute
  '/home/faqs': typeof HomeFaqsIndexRoute
  '/home/institution': typeof HomeInstitutionIndexRoute
  '/home/partners': typeof HomePartnersIndexRoute
  '/home/student-blog': typeof HomeStudentBlogIndexRoute
  '/home/university-search': typeof HomeUniversitySearchIndexRoute
  '/home/what-we-do': typeof HomeWhatWeDoIndexRoute
  '/home/why-feshia': typeof HomeWhyFeshiaIndexRoute
  '/admin/dashboard/investors/$investorId': typeof AdminDashboardInvestorsInvestorIdRoute
  '/admin/dashboard/transactions/payments': typeof AdminDashboardTransactionsPaymentsRoute
  '/admin/dashboard/transactions/receipts': typeof AdminDashboardTransactionsReceiptsRoute
  '/admin/dashboard/investors/': typeof AdminDashboardInvestorsIndexRoute
  '/admin/dashboard/prospects': typeof AdminDashboardProspectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/home': typeof HomeIndexRoute
  '/admin/dashboard/announcements': typeof AdminDashboardAnnouncementsRoute
  '/admin/dashboard/partners': typeof AdminDashboardPartnersRoute
  '/admin/dashboard/settings': typeof AdminDashboardSettingsRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/auth/admin': typeof AuthAdminIndexRoute
  '/home/about': typeof HomeAboutIndexRoute
  '/home/book-appointment': typeof HomeBookAppointmentIndexRoute
  '/home/consultant': typeof HomeConsultantIndexRoute
  '/home/events': typeof HomeEventsIndexRoute
  '/home/faqs': typeof HomeFaqsIndexRoute
  '/home/institution': typeof HomeInstitutionIndexRoute
  '/home/partners': typeof HomePartnersIndexRoute
  '/home/student-blog': typeof HomeStudentBlogIndexRoute
  '/home/university-search': typeof HomeUniversitySearchIndexRoute
  '/home/what-we-do': typeof HomeWhatWeDoIndexRoute
  '/home/why-feshia': typeof HomeWhyFeshiaIndexRoute
  '/admin/dashboard/investors/$investorId': typeof AdminDashboardInvestorsInvestorIdRoute
  '/admin/dashboard/transactions/payments': typeof AdminDashboardTransactionsPaymentsRoute
  '/admin/dashboard/transactions/receipts': typeof AdminDashboardTransactionsReceiptsRoute
  '/admin/dashboard/investors': typeof AdminDashboardInvestorsIndexRoute
  '/admin/dashboard/prospects': typeof AdminDashboardProspectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRouteRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRouteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/home/': typeof HomeIndexRoute
  '/admin/dashboard/announcements': typeof AdminDashboardAnnouncementsRoute
  '/admin/dashboard/investors': typeof AdminDashboardInvestorsRouteWithChildren
  '/admin/dashboard/partners': typeof AdminDashboardPartnersRoute
  '/admin/dashboard/settings': typeof AdminDashboardSettingsRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/auth/admin/': typeof AuthAdminIndexRoute
  '/home/about/': typeof HomeAboutIndexRoute
  '/home/book-appointment/': typeof HomeBookAppointmentIndexRoute
  '/home/consultant/': typeof HomeConsultantIndexRoute
  '/home/events/': typeof HomeEventsIndexRoute
  '/home/faqs/': typeof HomeFaqsIndexRoute
  '/home/institution/': typeof HomeInstitutionIndexRoute
  '/home/partners/': typeof HomePartnersIndexRoute
  '/home/student-blog/': typeof HomeStudentBlogIndexRoute
  '/home/university-search/': typeof HomeUniversitySearchIndexRoute
  '/home/what-we-do/': typeof HomeWhatWeDoIndexRoute
  '/home/why-feshia/': typeof HomeWhyFeshiaIndexRoute
  '/admin/dashboard/investors/$investorId': typeof AdminDashboardInvestorsInvestorIdRoute
  '/admin/dashboard/transactions/payments': typeof AdminDashboardTransactionsPaymentsRoute
  '/admin/dashboard/transactions/receipts': typeof AdminDashboardTransactionsReceiptsRoute
  '/admin/dashboard/investors/': typeof AdminDashboardInvestorsIndexRoute
  '/admin/dashboard/prospects/': typeof AdminDashboardProspectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/admin/dashboard'
    | '/admin'
    | '/home/'
    | '/admin/dashboard/announcements'
    | '/admin/dashboard/investors'
    | '/admin/dashboard/partners'
    | '/admin/dashboard/settings'
    | '/admin/dashboard/'
    | '/auth/admin'
    | '/home/about'
    | '/home/book-appointment'
    | '/home/consultant'
    | '/home/events'
    | '/home/faqs'
    | '/home/institution'
    | '/home/partners'
    | '/home/student-blog'
    | '/home/university-search'
    | '/home/what-we-do'
    | '/home/why-feshia'
    | '/admin/dashboard/investors/$investorId'
    | '/admin/dashboard/transactions/payments'
    | '/admin/dashboard/transactions/receipts'
    | '/admin/dashboard/investors/'
    | '/admin/dashboard/prospects'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/home'
    | '/admin/dashboard/announcements'
    | '/admin/dashboard/partners'
    | '/admin/dashboard/settings'
    | '/admin/dashboard'
    | '/auth/admin'
    | '/home/about'
    | '/home/book-appointment'
    | '/home/consultant'
    | '/home/events'
    | '/home/faqs'
    | '/home/institution'
    | '/home/partners'
    | '/home/student-blog'
    | '/home/university-search'
    | '/home/what-we-do'
    | '/home/why-feshia'
    | '/admin/dashboard/investors/$investorId'
    | '/admin/dashboard/transactions/payments'
    | '/admin/dashboard/transactions/receipts'
    | '/admin/dashboard/investors'
    | '/admin/dashboard/prospects'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/admin/dashboard'
    | '/admin/'
    | '/home/'
    | '/admin/dashboard/announcements'
    | '/admin/dashboard/investors'
    | '/admin/dashboard/partners'
    | '/admin/dashboard/settings'
    | '/admin/dashboard/'
    | '/auth/admin/'
    | '/home/about/'
    | '/home/book-appointment/'
    | '/home/consultant/'
    | '/home/events/'
    | '/home/faqs/'
    | '/home/institution/'
    | '/home/partners/'
    | '/home/student-blog/'
    | '/home/university-search/'
    | '/home/what-we-do/'
    | '/home/why-feshia/'
    | '/admin/dashboard/investors/$investorId'
    | '/admin/dashboard/transactions/payments'
    | '/admin/dashboard/transactions/receipts'
    | '/admin/dashboard/investors/'
    | '/admin/dashboard/prospects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
  AdminDashboardRouteRoute: typeof AdminDashboardRouteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/why-feshia/': {
      id: '/home/why-feshia/'
      path: '/why-feshia'
      fullPath: '/home/why-feshia'
      preLoaderRoute: typeof HomeWhyFeshiaIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/what-we-do/': {
      id: '/home/what-we-do/'
      path: '/what-we-do'
      fullPath: '/home/what-we-do'
      preLoaderRoute: typeof HomeWhatWeDoIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/university-search/': {
      id: '/home/university-search/'
      path: '/university-search'
      fullPath: '/home/university-search'
      preLoaderRoute: typeof HomeUniversitySearchIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/student-blog/': {
      id: '/home/student-blog/'
      path: '/student-blog'
      fullPath: '/home/student-blog'
      preLoaderRoute: typeof HomeStudentBlogIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/partners/': {
      id: '/home/partners/'
      path: '/partners'
      fullPath: '/home/partners'
      preLoaderRoute: typeof HomePartnersIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/institution/': {
      id: '/home/institution/'
      path: '/institution'
      fullPath: '/home/institution'
      preLoaderRoute: typeof HomeInstitutionIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/faqs/': {
      id: '/home/faqs/'
      path: '/faqs'
      fullPath: '/home/faqs'
      preLoaderRoute: typeof HomeFaqsIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/events/': {
      id: '/home/events/'
      path: '/events'
      fullPath: '/home/events'
      preLoaderRoute: typeof HomeEventsIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/consultant/': {
      id: '/home/consultant/'
      path: '/consultant'
      fullPath: '/home/consultant'
      preLoaderRoute: typeof HomeConsultantIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/book-appointment/': {
      id: '/home/book-appointment/'
      path: '/book-appointment'
      fullPath: '/home/book-appointment'
      preLoaderRoute: typeof HomeBookAppointmentIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/about/': {
      id: '/home/about/'
      path: '/about'
      fullPath: '/home/about'
      preLoaderRoute: typeof HomeAboutIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/auth/admin/': {
      id: '/auth/admin/'
      path: '/auth/admin'
      fullPath: '/auth/admin'
      preLoaderRoute: typeof AuthAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin/dashboard/settings': {
      id: '/admin/dashboard/settings'
      path: '/settings'
      fullPath: '/admin/dashboard/settings'
      preLoaderRoute: typeof AdminDashboardSettingsRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin/dashboard/partners': {
      id: '/admin/dashboard/partners'
      path: '/partners'
      fullPath: '/admin/dashboard/partners'
      preLoaderRoute: typeof AdminDashboardPartnersRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin/dashboard/investors': {
      id: '/admin/dashboard/investors'
      path: '/investors'
      fullPath: '/admin/dashboard/investors'
      preLoaderRoute: typeof AdminDashboardInvestorsRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin/dashboard/announcements': {
      id: '/admin/dashboard/announcements'
      path: '/announcements'
      fullPath: '/admin/dashboard/announcements'
      preLoaderRoute: typeof AdminDashboardAnnouncementsRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin/dashboard/prospects/': {
      id: '/admin/dashboard/prospects/'
      path: '/prospects'
      fullPath: '/admin/dashboard/prospects'
      preLoaderRoute: typeof AdminDashboardProspectsIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin/dashboard/investors/': {
      id: '/admin/dashboard/investors/'
      path: '/'
      fullPath: '/admin/dashboard/investors/'
      preLoaderRoute: typeof AdminDashboardInvestorsIndexRouteImport
      parentRoute: typeof AdminDashboardInvestorsRoute
    }
    '/admin/dashboard/transactions/receipts': {
      id: '/admin/dashboard/transactions/receipts'
      path: '/transactions/receipts'
      fullPath: '/admin/dashboard/transactions/receipts'
      preLoaderRoute: typeof AdminDashboardTransactionsReceiptsRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin/dashboard/transactions/payments': {
      id: '/admin/dashboard/transactions/payments'
      path: '/transactions/payments'
      fullPath: '/admin/dashboard/transactions/payments'
      preLoaderRoute: typeof AdminDashboardTransactionsPaymentsRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin/dashboard/investors/$investorId': {
      id: '/admin/dashboard/investors/$investorId'
      path: '/$investorId'
      fullPath: '/admin/dashboard/investors/$investorId'
      preLoaderRoute: typeof AdminDashboardInvestorsInvestorIdRouteImport
      parentRoute: typeof AdminDashboardInvestorsRoute
    }
  }
}

interface HomeRouteRouteChildren {
  HomeIndexRoute: typeof HomeIndexRoute
  HomeAboutIndexRoute: typeof HomeAboutIndexRoute
  HomeBookAppointmentIndexRoute: typeof HomeBookAppointmentIndexRoute
  HomeConsultantIndexRoute: typeof HomeConsultantIndexRoute
  HomeEventsIndexRoute: typeof HomeEventsIndexRoute
  HomeFaqsIndexRoute: typeof HomeFaqsIndexRoute
  HomeInstitutionIndexRoute: typeof HomeInstitutionIndexRoute
  HomePartnersIndexRoute: typeof HomePartnersIndexRoute
  HomeStudentBlogIndexRoute: typeof HomeStudentBlogIndexRoute
  HomeUniversitySearchIndexRoute: typeof HomeUniversitySearchIndexRoute
  HomeWhatWeDoIndexRoute: typeof HomeWhatWeDoIndexRoute
  HomeWhyFeshiaIndexRoute: typeof HomeWhyFeshiaIndexRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeIndexRoute: HomeIndexRoute,
  HomeAboutIndexRoute: HomeAboutIndexRoute,
  HomeBookAppointmentIndexRoute: HomeBookAppointmentIndexRoute,
  HomeConsultantIndexRoute: HomeConsultantIndexRoute,
  HomeEventsIndexRoute: HomeEventsIndexRoute,
  HomeFaqsIndexRoute: HomeFaqsIndexRoute,
  HomeInstitutionIndexRoute: HomeInstitutionIndexRoute,
  HomePartnersIndexRoute: HomePartnersIndexRoute,
  HomeStudentBlogIndexRoute: HomeStudentBlogIndexRoute,
  HomeUniversitySearchIndexRoute: HomeUniversitySearchIndexRoute,
  HomeWhatWeDoIndexRoute: HomeWhatWeDoIndexRoute,
  HomeWhyFeshiaIndexRoute: HomeWhyFeshiaIndexRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

interface AdminDashboardInvestorsRouteChildren {
  AdminDashboardInvestorsInvestorIdRoute: typeof AdminDashboardInvestorsInvestorIdRoute
  AdminDashboardInvestorsIndexRoute: typeof AdminDashboardInvestorsIndexRoute
}

const AdminDashboardInvestorsRouteChildren: AdminDashboardInvestorsRouteChildren =
  {
    AdminDashboardInvestorsInvestorIdRoute:
      AdminDashboardInvestorsInvestorIdRoute,
    AdminDashboardInvestorsIndexRoute: AdminDashboardInvestorsIndexRoute,
  }

const AdminDashboardInvestorsRouteWithChildren =
  AdminDashboardInvestorsRoute._addFileChildren(
    AdminDashboardInvestorsRouteChildren,
  )

interface AdminDashboardRouteRouteChildren {
  AdminDashboardAnnouncementsRoute: typeof AdminDashboardAnnouncementsRoute
  AdminDashboardInvestorsRoute: typeof AdminDashboardInvestorsRouteWithChildren
  AdminDashboardPartnersRoute: typeof AdminDashboardPartnersRoute
  AdminDashboardSettingsRoute: typeof AdminDashboardSettingsRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminDashboardTransactionsPaymentsRoute: typeof AdminDashboardTransactionsPaymentsRoute
  AdminDashboardTransactionsReceiptsRoute: typeof AdminDashboardTransactionsReceiptsRoute
  AdminDashboardProspectsIndexRoute: typeof AdminDashboardProspectsIndexRoute
}

const AdminDashboardRouteRouteChildren: AdminDashboardRouteRouteChildren = {
  AdminDashboardAnnouncementsRoute: AdminDashboardAnnouncementsRoute,
  AdminDashboardInvestorsRoute: AdminDashboardInvestorsRouteWithChildren,
  AdminDashboardPartnersRoute: AdminDashboardPartnersRoute,
  AdminDashboardSettingsRoute: AdminDashboardSettingsRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminDashboardTransactionsPaymentsRoute:
    AdminDashboardTransactionsPaymentsRoute,
  AdminDashboardTransactionsReceiptsRoute:
    AdminDashboardTransactionsReceiptsRoute,
  AdminDashboardProspectsIndexRoute: AdminDashboardProspectsIndexRoute,
}

const AdminDashboardRouteRouteWithChildren =
  AdminDashboardRouteRoute._addFileChildren(AdminDashboardRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRouteRoute: HomeRouteRouteWithChildren,
  AdminDashboardRouteRoute: AdminDashboardRouteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AuthAdminIndexRoute: AuthAdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
