/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteRouteImport } from './routes/home/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as HomeStudentBlogIndexRouteImport } from './routes/home/student-blog/index'
import { Route as HomeBookAppointmentIndexRouteImport } from './routes/home/book-appointment/index'

const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeStudentBlogIndexRoute = HomeStudentBlogIndexRouteImport.update({
  id: '/student-blog/',
  path: '/student-blog/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeBookAppointmentIndexRoute =
  HomeBookAppointmentIndexRouteImport.update({
    id: '/book-appointment/',
    path: '/book-appointment/',
    getParentRoute: () => HomeRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRouteRouteWithChildren
  '/home/': typeof HomeIndexRoute
  '/home/book-appointment': typeof HomeBookAppointmentIndexRoute
  '/home/student-blog': typeof HomeStudentBlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeIndexRoute
  '/home/book-appointment': typeof HomeBookAppointmentIndexRoute
  '/home/student-blog': typeof HomeStudentBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRouteRouteWithChildren
  '/home/': typeof HomeIndexRoute
  '/home/book-appointment/': typeof HomeBookAppointmentIndexRoute
  '/home/student-blog/': typeof HomeStudentBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/home/'
    | '/home/book-appointment'
    | '/home/student-blog'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/home' | '/home/book-appointment' | '/home/student-blog'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/home/'
    | '/home/book-appointment/'
    | '/home/student-blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/student-blog/': {
      id: '/home/student-blog/'
      path: '/student-blog'
      fullPath: '/home/student-blog'
      preLoaderRoute: typeof HomeStudentBlogIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/book-appointment/': {
      id: '/home/book-appointment/'
      path: '/book-appointment'
      fullPath: '/home/book-appointment'
      preLoaderRoute: typeof HomeBookAppointmentIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
  }
}

interface HomeRouteRouteChildren {
  HomeIndexRoute: typeof HomeIndexRoute
  HomeBookAppointmentIndexRoute: typeof HomeBookAppointmentIndexRoute
  HomeStudentBlogIndexRoute: typeof HomeStudentBlogIndexRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeIndexRoute: HomeIndexRoute,
  HomeBookAppointmentIndexRoute: HomeBookAppointmentIndexRoute,
  HomeStudentBlogIndexRoute: HomeStudentBlogIndexRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRouteRoute: HomeRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
